2020-08-17 14:04:37,333 : INFO : Start of Prediction
2020-08-17 14:04:37,334 : INFO : run_id:2020-08-17_140437_846227986
2020-08-17 14:04:37,334 : INFO : Start of Data Load, validation and transformation
2020-08-17 14:04:37,334 : INFO : Start of Archiving Old Rejected Files...
2020-08-17 14:04:37,334 : INFO : End of Archiving Old Rejected Files...
2020-08-17 14:04:37,334 : INFO : Start of Archiving Old Validated Files...
2020-08-17 14:04:37,334 : INFO : End of Archiving Old Validated Files...
2020-08-17 14:04:37,334 : INFO : Start of Archiving Old Processed Files...
2020-08-17 14:04:37,334 : INFO : End of Archiving Old Processed Files...
2020-08-17 14:04:37,334 : INFO : Start of Archiving Old Result Files...
2020-08-17 14:04:37,334 : INFO : End of Archiving Old Result Files...
2020-08-17 14:04:37,334 : INFO : Start of Reading values From Schema...
2020-08-17 14:04:37,334 : INFO : End of Reading values From Schema...
2020-08-17 14:04:37,335 : INFO : Start of Validating Column Length...
2020-08-17 14:04:37,335 : INFO : End of Validating Column Length...
2020-08-17 14:04:37,335 : INFO : Start of Validating Missing Values...
2020-08-17 14:04:37,335 : INFO : End of Validating Missing Values...
2020-08-17 14:04:37,335 : INFO : Start of Replacing Missing Values with NULL...
2020-08-17 14:04:37,336 : INFO : End of Replacing Missing Values with NULL...
2020-08-17 14:04:37,336 : INFO : Start of Creating Table...
2020-08-17 14:04:37,336 : INFO : Opened prediction database successfully
2020-08-17 14:04:37,350 : INFO : CREATE TABLE prediction_raw_data_t column_name
2020-08-17 14:04:37,356 : INFO : ALTER TABLE prediction_raw_data_t ADD COLUMN
2020-08-17 14:04:37,362 : INFO : ALTER TABLE prediction_raw_data_t ADD COLUMN
2020-08-17 14:04:37,368 : INFO : ALTER TABLE prediction_raw_data_t ADD COLUMN
2020-08-17 14:04:37,374 : INFO : ALTER TABLE prediction_raw_data_t ADD COLUMN
2020-08-17 14:04:37,380 : INFO : ALTER TABLE prediction_raw_data_t ADD COLUMN
2020-08-17 14:04:37,385 : INFO : ALTER TABLE prediction_raw_data_t ADD COLUMN
2020-08-17 14:04:37,391 : INFO : ALTER TABLE prediction_raw_data_t ADD COLUMN
2020-08-17 14:04:37,396 : INFO : ALTER TABLE prediction_raw_data_t ADD COLUMN
2020-08-17 14:04:37,396 : INFO : End of Creating Table...
2020-08-17 14:04:37,396 : INFO : Opened prediction database successfully
2020-08-17 14:04:37,397 : INFO : Start of Inserting Data into Table...
2020-08-17 14:04:37,397 : INFO : End of Inserting Data into Table...
2020-08-17 14:04:37,397 : INFO : Start of Exporting Data into CSV...
2020-08-17 14:04:37,397 : INFO : Opened prediction database successfully
2020-08-17 14:04:37,397 : INFO : End of Exporting Data into CSV...
2020-08-17 14:04:37,397 : INFO : Start of Moving Processed Files...
2020-08-17 14:04:37,397 : INFO : End of Moving Processed Files...
2020-08-17 14:04:37,397 : INFO : End of Data Load, validation and transformation
2020-08-17 14:04:37,397 : INFO : Start of Preprocessing...
2020-08-17 14:04:37,398 : INFO : Start of reading dataset...
2020-08-17 14:04:37,401 : INFO : End of reading dataset...
2020-08-17 14:04:37,401 : INFO : Start of feature encoding...
2020-08-17 14:04:37,424 : INFO : End of feature encoding...
2020-08-17 14:04:37,424 : INFO : Start of Droping Columns...
2020-08-17 14:04:37,425 : INFO : End of Droping Columns...
2020-08-17 14:04:37,425 : INFO : Start of finding missing values...
2020-08-17 14:04:37,426 : INFO : End of finding missing values...
2020-08-17 14:04:37,426 : INFO : Start of building final predictset...
2020-08-17 14:04:37,429 : INFO : End of building final predictset...
2020-08-17 14:04:37,429 : INFO : End of Preprocessing...
2020-08-17 14:04:37,430 : INFO : Start of Load Model
2020-08-17 14:04:37,430 : INFO : Model File KMeans loaded
2020-08-17 14:04:37,430 : INFO : End of Load Model
2020-08-17 14:04:37,431 : ERROR : Unsuccessful End of Prediction
Traceback (most recent call last):
  File "/home/jitendra/mle2e/p1/ML-end-end/apps/prediction/predict_model.py", line 38, in batch_predict_from_model
    clusters = kmeans.predict(self.X.drop(['empid'],axis=1))
  File "/home/jitendra/anaconda3/lib/python3.7/site-packages/sklearn/cluster/_kmeans.py", line 1087, in predict
    X = self._check_test_data(X)
  File "/home/jitendra/anaconda3/lib/python3.7/site-packages/sklearn/cluster/_kmeans.py", line 811, in _check_test_data
    X = check_array(X, accept_sparse='csr', dtype=FLOAT_DTYPES)
  File "/home/jitendra/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py", line 586, in check_array
    context))
ValueError: Found array with 0 sample(s) (shape=(0, 9)) while a minimum of 1 is required.
